# This file was auto-generated by Fern from our API Definition.

from .environment import DoptApiEnvironment
from .resources.groups.client import AsyncGroupsClient, GroupsClient
from .resources.users.client import AsyncUsersClient, UsersClient


class DoptApi:
    def __init__(self, *, environment: DoptApiEnvironment = DoptApiEnvironment.DEFAULT, api_key: str):
        self._environment = environment
        self.api_key = api_key
        self.users = UsersClient(environment=self._environment, api_key=self.api_key)
        self.groups = GroupsClient(environment=self._environment, api_key=self.api_key)


class AsyncDoptApi:
    def __init__(self, *, environment: DoptApiEnvironment = DoptApiEnvironment.DEFAULT, api_key: str):
        self._environment = environment
        self.api_key = api_key
        self.users = AsyncUsersClient(environment=self._environment, api_key=self.api_key)
        self.groups = AsyncGroupsClient(environment=self._environment, api_key=self.api_key)
