# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.bad_request_error_response_body import BadRequestErrorResponseBody


class BadRequestError(ApiError):
    def __init__(self, body: BadRequestErrorResponseBody):
        super().__init__(status_code=400, body=body)
