# This file was auto-generated by Fern from our API Definition.

import typing

from .identify_segment_request_body_identify_segment_request_body import (
    IdentifySegmentRequestBodyIdentifySegmentRequestBody,
)

IdentifySegmentRequestBody = typing.Union[
    IdentifySegmentRequestBodyIdentifySegmentRequestBody, IdentifySegmentRequestBodyIdentifySegmentRequestBody
]
