# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .identify_segment_request_body_group import IdentifySegmentRequestBodyGroup
from .identify_segment_request_body_identify import IdentifySegmentRequestBodyIdentify


class IdentifySegmentRequestBody_Identify(IdentifySegmentRequestBodyIdentify):
    type: typing_extensions.Literal["identify"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class IdentifySegmentRequestBody_Group(IdentifySegmentRequestBodyGroup):
    type: typing_extensions.Literal["group"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


IdentifySegmentRequestBody = typing.Union[IdentifySegmentRequestBody_Identify, IdentifySegmentRequestBody_Group]
