# This file was auto-generated by Fern from our API Definition.

import typing

from .identify_batch_request_body_item import IdentifyBatchRequestBodyItem

IdentifyBatchRequestBody = typing.List[IdentifyBatchRequestBodyItem]
